### ISSUE TITLE
Change react-refresh/only-export-components to error

### ISSUE THREAD

**Issue by stropitek** [cheminfo/eslint-config-cheminfo-react#38]
I'd be in favour of making this an error because we don't pay too much attention to warnings in PRs and after some time we end up with a lot of those and they make it harder to pay attention to more important warnings like TODOs.

It's a bit tedious if there are many but straightforward to fix.

WDYT @cheminfo/collaborators ?

**Comment by tpoisseau** [comment]
Some times, this rule can be annoying to apply (like a constant used by a component and exported). But I agree, applying this rule leads to a better developer experience in long term. And do not apply it, can lead to weird bug during dev.

So go switch this rule to error.

**Comment by targos** [comment]
When I added this rule the intention was to switch to error at some point while allowing to incrementally fix it first. If people don't care about it and tend to introduce more warnings then sure, we can switch to error right now.
